### ISSUE TITLE
Node version?

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/gavel#12]
We may be implementing a Node.js version. Subscribe to this issue if you're interested in contributing to that!

**Comment by dawsonbotsford** [comment]
I'm interested! Keep me up to date 👍

**Comment by lkwatson** [comment]
I'm interested as well!

**Comment by louisgv** [comment]
Can totally help out on this whenever it is up.

**Comment by phoenix1796** [comment]
Interested in Contributing :smile: :+1:

**Comment by anishathalye** [comment]
Okay, so I have a question about this:

1. Will porting Gavel to Node have an impact on adoption?
2. Will porting Gavel to Node have an impact on contributions?

There are some cons to using Node:

* There isn't anything like NumPy/SciPy in Node. I don't think we're using anything too fancy right now, and there are packages like [math-betaln](https://www.npmjs.com/package/math-betaln) and [math-digamma](https://www.npmjs.com/package/math-digamma) for node. But if we want to change the algorithm in the future, using Node is probably more painful.

Thoughts?

**Comment by dawsonbotsford** [comment]
1. It is the most popular language for open-sourced code rn. 
2. It will increase the amount of contributions because people can more easily understand and create code (since it's the most popular langauge for open-sourced code). 

It's a decision primarily on you whether the algorithm would work well with node. It's currently a stretch for non-mathematicians to work with and understand the algorithm, either way, so think about it from the end-goal perspective. If you want to have more contributions there's no doubt node would be better. If you want to have easier to work with, more performant algorithms stick with Python

**Comment by anishathalye** [comment]
Hmm, that makes sense. I'll try experimenting with a Node version this weekend.

**Comment by lkwatson** [comment]
Why not have the server run in Node, and then have the data parsing done in python?

**Comment by phoenix1796** [comment]
I agree with @lkwatson , because JS does have a very odd way of handling mathematical operations sometimes and they could cause problems

P.S. Just to avoid a flame war here , I am a JS Junkie but while working on Node i have found it to be better suited to creating I/O bound programs rather than mathematical programs which are CPU-Bound.
:smile:

**Comment by anishathalye** [comment]
Well, I think given the size of most hackathons, judging is neither I/O nor CPU-bound, it's bound by how quickly judges input scores. 😛

Hmm, are there any clean ways of having a server in Node but the data processing done in Python?
(oh, also, we could look into rewriting it in C/C++ and use node-gyp?)

**Comment by lkwatson** [comment]
If you keep both a Node and Python server up, they can communicate over sockets (assuming you're on unix).

**Comment by phoenix1796** [comment]
Or a naive but portable solutioncould be to host a python server on localhost and send data from node to python using http requests.

**Comment by dawsonbotsford** [comment]
It's not very reliable to communicate over localhost to another process on the exact same machine and expect them not to crash. When either one of the languages running has an uncaught error it would take down the other process. 

Instead I'd vote that the Python be modified and ran within a package like [python-shell](https://github.com/extrabacon/python-shell) which allows you to execute and pass arguments to Python functions inline in your JavaScript.

**Comment by joshuamorton** [comment]
From a completely self-serving perspective (as a pythonist and no-good-reason node-hater), stick with python!

From a more realistic perspective, the two hardest parts of the port would be writing (good, safe) js version of betaln and psi, because there aren't existing implementations, but math.js has a gamma function, which is all you need for betaln and most of what you need for psi.

**Comment by anishathalye** [comment]
Okay, I don't think this is going to happen / I don't think it's worth the effort, so I'm closing the issue.

If anyone has a reason to reopen it at any point, feel free.

**Comment by lappalj4** [comment]
Hey Anish and others - never saw this earlier, but we at Junction have in fact begun work on a [Node/React version](https://github.com/hackjunction/node-gavel) this year which would support peer reviewing and some other new features as well - it is rather incomplete at the moment but we aim to have some version of it ready for our main event at the end of November. I will certainly update here on the progress and status of that as we move forward with it.

**Comment by anishathalye** [comment]
What's the reason to port Gavel to node? I don't think it makes sense to maintain the same software implemented in multiple languages, in the long-term.

The UI improvements sound like a great idea, and peer judging sounds cool. Why not implement those on top of the Python version?

**Comment by lappalj4** [comment]
Ah, as such the project is not really meant to replace Gavel, but rather implement the Gavel-style judging logic inside of a larger platform.

The main reason for why Node is just that all of our other projects are (will be, at least) on the Node.js/React/Mongo stack, and also that some of the changes we are making are rather significant in nature so we decided that it would be at least as much work to start editing the existing one. 

The idea for what we are building is that it would be an all-in-one platform for submissions, judging and showcasing submissions, and that a single deployment could be used across multiple events.
