### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by manojpandey** [anishathalye/gavel#17]
pre-commit hook would be great to have to check for code styling and adhere to standard pythonic code guidelines

Ex. http://pre-commit.com/

**Comment by anishathalye** [comment]
This looks nice.

Hm, I wonder if we could do something as part of CI rather than having a pre-commit hook, so it happens before stuff is merged into master, but not while people are working on developing stuff.

**Comment by manojpandey** [comment]
Then, best would be to have a pre-commit hook + CI configured 👍

**Comment by anishathalye** [comment]
At this point, the pre-commit hook might be too much effort and might actually end up raising the barrier for people to contribute. I think we can take care of code style issues and stuff during the pull request process.

Having CI at some point would be nice, though, but I think that's more important for tests rather than code style checks.
